// Test generated by RoostGPT for test Reacttest_1 using AI Type Open AI and AI Model gpt-4-1106-preview


// src/App.tsx

import React from 'react';

interface AppProps {
  title: string;
}

const App: React.FC<AppProps> = ({ title }) => {
  return (
    <div data-testid="app-container">
      <h1 data-testid="app-title">{title}</h1>
    </div>
  );
};

App.defaultProps = {
  title: 'Default App Title',
};

export default App;
